name: firebase_authentication_tutorial
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  # maybe upgrade to sdk: ">=2.12.0 <3.0.0" to allow some firebase functions

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  #Firebase
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase_storage: ^4.0.1
  flutter_icons: ^1.0.0+1
  cloud_firestore: ^0.14.3+1

  # slidable
  flutter_slidable: ^0.5.7
  provider: ^4.3.2+1

  # others
  image_picker: ^0.6.4
  get_it: ^4.0.1
  google_sign_in: ^4.4.0

  # testing
  http: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # add test:
  # add mockito
  # add build_runner

flutter:
  uses-material-design: true
